### ISSUE TITLE
[Curiosity] about config path

### ISSUE THREAD

**Issue by maxdevjs** [sharpvik/gpt#2]
Hello,

first of all, thank you for sharing this project.

Relative to https://github.com/sharpvik/gpt/blob/77206e971031ed1d9af654bbe840340b50aae309/home/home.go#L15 I wonder if it would be viable to use [UserConfigDir](https://pkg.go.dev/os#UserConfigDir)  instead.

**Comment by sharpvik** [comment]
Hey @maxdevjs, thanks for asking. It's totally possible. My initial choice to go with the `$HOME` folder was dictated by the fact that 

1. it's a bit more universal and 
2. it's not really a config that I'm storing there

I drew inspiration from how shells (like bash and zsh) store their stuff in the home folder as `.bashrc` and `.zshrc`.
